#!/usr/bin/env python
"""Move DOF.

Usage:
  moveDof backup <address> [--output-file=<of> | -o <of>]
  moveDof move <from-address> <to-address>
  moveDof (-h | --help)

Options:
  -h --help                   Show this screen.
  -o <of> --output-file=<of>  Store the parameters in a file, default is stdout.
"""
from docopt import docopt

if __name__ == '__main__':
    arguments = docopt(__doc__, version='Naval Fate 2.0')
    print arguments
    